//traer datos mocakaroo
const mails_raw = `

[{
    "id": 1,
    "sender": "Leigh",
    "senderImg": "http://dummyimage.com/157x100.jpg/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-07-04T11:35:21Z",
    "subject": "suspendisse potenti nullam porttitor lacus at turpis donec posuere",
    "body": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 2,
    "sender": "Auberta",
    "senderImg": "http://dummyimage.com/236x243.png/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-07-22T09:27:55Z",
    "subject": "ante",
    "body": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 3,
    "sender": "Hiram",
    "senderImg": "http://dummyimage.com/112x164.jpg/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-05-25T17:43:49Z",
    "subject": "magna ac consequat metus sapien ut nunc",
    "body": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "promotions",
    "folder": "personal"
  }, {
    "id": 4,
    "sender": "Saundra",
    "senderImg": "http://dummyimage.com/207x214.png/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-03-17T19:48:19Z",
    "subject": "nunc rhoncus",
    "body": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 5,
    "sender": "Annmaria",
    "senderImg": "http://dummyimage.com/130x245.bmp/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-01-22T07:30:40Z",
    "subject": "nibh in lectus",
    "body": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 6,
    "sender": "Millisent",
    "senderImg": "http://dummyimage.com/234x207.bmp/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-04-30T19:12:19Z",
    "subject": "iaculis diam erat fermentum justo nec condimentum neque",
    "body": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "work"
  }, {
    "id": 7,
    "sender": "Roldan",
    "senderImg": "http://dummyimage.com/245x202.png/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-05-16T18:03:14Z",
    "subject": "molestie",
    "body": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 8,
    "sender": "Sue",
    "senderImg": "http://dummyimage.com/227x141.png/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-02-23T01:16:48Z",
    "subject": "sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante",
    "body": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 9,
    "sender": "Hinze",
    "senderImg": "http://dummyimage.com/168x106.png/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-06-11T23:17:15Z",
    "subject": "sapien iaculis",
    "body": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 10,
    "sender": "Arvy",
    "senderImg": "http://dummyimage.com/152x187.png/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2021-01-04T08:11:06Z",
    "subject": "faucibus orci luctus et ultrices posuere cubilia curae donec pharetra",
    "body": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 11,
    "sender": "Yasmeen",
    "senderImg": "http://dummyimage.com/127x194.jpg/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-07-11T07:02:32Z",
    "subject": "amet erat nulla tempus vivamus in felis eu sapien cursus",
    "body": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 12,
    "sender": "Celle",
    "senderImg": "http://dummyimage.com/167x216.png/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-06-16T08:03:06Z",
    "subject": "aliquam convallis nunc proin at turpis",
    "body": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 13,
    "sender": "Standford",
    "senderImg": "http://dummyimage.com/174x128.png/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-07-15T03:50:02Z",
    "subject": "nec condimentum neque",
    "body": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 14,
    "sender": "Arvie",
    "senderImg": "http://dummyimage.com/134x123.bmp/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2020-10-08T03:59:26Z",
    "subject": "vel pede morbi porttitor lorem id ligula suspendisse ornare",
    "body": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 15,
    "sender": "Jamima",
    "senderImg": "http://dummyimage.com/189x226.jpg/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-07-26T09:25:11Z",
    "subject": "erat id",
    "body": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 16,
    "sender": "Allie",
    "senderImg": "http://dummyimage.com/137x199.png/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-05-14T19:23:52Z",
    "subject": "duis consequat dui nec nisi volutpat eleifend",
    "body": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": true,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 17,
    "sender": "Amie",
    "senderImg": "http://dummyimage.com/134x139.jpg/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-02-26T01:40:15Z",
    "subject": "risus praesent lectus vestibulum quam sapien varius",
    "body": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": true,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 18,
    "sender": "Neille",
    "senderImg": "http://dummyimage.com/219x215.png/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-04-30T11:17:16Z",
    "subject": "porttitor pede",
    "body": "Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 19,
    "sender": "Elsy",
    "senderImg": "http://dummyimage.com/197x131.png/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-02-06T13:32:04Z",
    "subject": "vestibulum velit id pretium iaculis",
    "body": "In congue. Etiam justo. Etiam pretium iaculis justo.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 20,
    "sender": "Valeda",
    "senderImg": "http://dummyimage.com/168x148.jpg/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-05-03T01:08:46Z",
    "subject": "cras in purus",
    "body": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 21,
    "sender": "Armando",
    "senderImg": "http://dummyimage.com/205x143.png/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-06-23T20:57:13Z",
    "subject": "quisque",
    "body": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 22,
    "sender": "Bunny",
    "senderImg": "http://dummyimage.com/221x200.png/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2020-08-14T14:52:10Z",
    "subject": "turpis elementum ligula vehicula consequat morbi",
    "body": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": true,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 23,
    "sender": "Gerald",
    "senderImg": "http://dummyimage.com/143x247.bmp/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-09-13T05:44:08Z",
    "subject": "vestibulum sed magna at nunc commodo placerat",
    "body": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 24,
    "sender": "Caye",
    "senderImg": "http://dummyimage.com/173x104.bmp/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-01-26T19:24:21Z",
    "subject": "eleifend luctus ultricies",
    "body": "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 25,
    "sender": "Kippie",
    "senderImg": "http://dummyimage.com/228x166.bmp/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-08-11T07:56:30Z",
    "subject": "tortor duis mattis egestas metus aenean fermentum donec ut mauris",
    "body": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "work"
  }, {
    "id": 26,
    "sender": "Arleta",
    "senderImg": "http://dummyimage.com/104x162.png/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-11-08T05:00:37Z",
    "subject": "nulla pede ullamcorper augue a suscipit nulla elit ac nulla",
    "body": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 27,
    "sender": "Braden",
    "senderImg": "http://dummyimage.com/185x112.bmp/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2021-01-19T12:19:46Z",
    "subject": "felis",
    "body": "Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 28,
    "sender": "Evangelin",
    "senderImg": "http://dummyimage.com/123x163.png/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-04-16T02:48:12Z",
    "subject": "luctus ultricies eu nibh quisque",
    "body": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "social",
    "folder": "work"
  }, {
    "id": 29,
    "sender": "Curtice",
    "senderImg": "http://dummyimage.com/139x245.bmp/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-07-08T19:06:06Z",
    "subject": "ultricies",
    "body": "In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 30,
    "sender": "Leonie",
    "senderImg": "http://dummyimage.com/118x145.bmp/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-05-01T13:14:59Z",
    "subject": "ac tellus semper interdum",
    "body": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "work"
  }, {
    "id": 31,
    "sender": "De witt",
    "senderImg": "http://dummyimage.com/192x159.png/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-09-01T19:19:42Z",
    "subject": "habitasse platea dictumst",
    "body": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 32,
    "sender": "Laureen",
    "senderImg": "http://dummyimage.com/112x154.jpg/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-10-14T03:40:54Z",
    "subject": "rutrum nulla nunc purus",
    "body": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "personal"
  }, {
    "id": 33,
    "sender": "Merrick",
    "senderImg": "http://dummyimage.com/231x191.bmp/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-01-30T01:19:07Z",
    "subject": "nunc commodo placerat praesent blandit nam nulla integer",
    "body": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 34,
    "sender": "Louise",
    "senderImg": "http://dummyimage.com/206x195.jpg/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-08-02T14:20:33Z",
    "subject": "mattis egestas metus aenean fermentum donec ut mauris eget",
    "body": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 35,
    "sender": "Karim",
    "senderImg": "http://dummyimage.com/118x142.bmp/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-02-27T06:30:41Z",
    "subject": "in",
    "body": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 36,
    "sender": "Rice",
    "senderImg": "http://dummyimage.com/161x199.jpg/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-01-23T18:06:16Z",
    "subject": "primis in",
    "body": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "promotions",
    "folder": "personal"
  }, {
    "id": 37,
    "sender": "Alfred",
    "senderImg": "http://dummyimage.com/245x173.bmp/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-01-30T14:19:45Z",
    "subject": "vel sem sed sagittis nam",
    "body": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 38,
    "sender": "Rodolph",
    "senderImg": "http://dummyimage.com/166x123.bmp/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-07-26T15:20:01Z",
    "subject": "proin eu mi nulla ac enim in tempor turpis",
    "body": "Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 39,
    "sender": "Sigmund",
    "senderImg": "http://dummyimage.com/154x171.png/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-12-17T02:20:09Z",
    "subject": "congue risus semper porta volutpat quam pede",
    "body": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 40,
    "sender": "Korry",
    "senderImg": "http://dummyimage.com/147x157.jpg/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-08-23T02:10:56Z",
    "subject": "justo lacinia eget tincidunt eget tempus vel",
    "body": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "promotions",
    "folder": "personal"
  }, {
    "id": 41,
    "sender": "Merrily",
    "senderImg": "http://dummyimage.com/170x247.png/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-04-28T02:12:04Z",
    "subject": "pede justo eu",
    "body": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": false,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 42,
    "sender": "Dorette",
    "senderImg": "http://dummyimage.com/125x175.png/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-12-21T08:10:51Z",
    "subject": "in sagittis dui vel nisl duis ac",
    "body": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 43,
    "sender": "Charmine",
    "senderImg": "http://dummyimage.com/158x231.png/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-10-06T12:00:54Z",
    "subject": "id ligula suspendisse ornare consequat lectus in est risus auctor",
    "body": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 44,
    "sender": "Amber",
    "senderImg": "http://dummyimage.com/200x217.bmp/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2020-10-29T07:12:49Z",
    "subject": "in",
    "body": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "personal"
  }, {
    "id": 45,
    "sender": "Berky",
    "senderImg": "http://dummyimage.com/130x218.jpg/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-06-17T16:59:00Z",
    "subject": "tellus nulla ut erat id",
    "body": "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 46,
    "sender": "Milissent",
    "senderImg": "http://dummyimage.com/186x183.png/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-04-28T01:01:51Z",
    "subject": "fusce",
    "body": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 47,
    "sender": "Janos",
    "senderImg": "http://dummyimage.com/213x229.bmp/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2020-11-20T22:45:00Z",
    "subject": "sit",
    "body": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 48,
    "sender": "Carlotta",
    "senderImg": "http://dummyimage.com/240x127.bmp/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-12-01T21:12:56Z",
    "subject": "nulla sed vel enim sit",
    "body": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 49,
    "sender": "Gusti",
    "senderImg": "http://dummyimage.com/230x198.jpg/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-12-01T22:27:36Z",
    "subject": "tellus nulla ut erat id",
    "body": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "personal"
  }, {
    "id": 50,
    "sender": "Persis",
    "senderImg": "http://dummyimage.com/116x201.png/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-10-05T13:26:25Z",
    "subject": "aliquam erat",
    "body": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 51,
    "sender": "Leonore",
    "senderImg": "http://dummyimage.com/213x100.jpg/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2021-01-07T00:20:11Z",
    "subject": "imperdiet sapien urna pretium",
    "body": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 52,
    "sender": "Katrinka",
    "senderImg": "http://dummyimage.com/152x146.jpg/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2020-06-06T08:59:03Z",
    "subject": "amet",
    "body": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 53,
    "sender": "Wainwright",
    "senderImg": "http://dummyimage.com/199x134.jpg/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-10-23T01:58:52Z",
    "subject": "nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum",
    "body": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 54,
    "sender": "Annamarie",
    "senderImg": "http://dummyimage.com/201x163.png/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-12-18T07:22:43Z",
    "subject": "nec molestie sed justo pellentesque",
    "body": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 55,
    "sender": "Griff",
    "senderImg": "http://dummyimage.com/202x110.bmp/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-01-31T09:29:47Z",
    "subject": "id massa id nisl venenatis",
    "body": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 56,
    "sender": "Hart",
    "senderImg": "http://dummyimage.com/226x197.jpg/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-05-01T21:26:57Z",
    "subject": "rhoncus aliquet pulvinar sed",
    "body": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 57,
    "sender": "Mickie",
    "senderImg": "http://dummyimage.com/158x238.bmp/dddddd/000000",
    "adjunto": true,
    "sendDate": "2020-12-24T09:29:15Z",
    "subject": "iaculis diam erat fermentum justo nec condimentum neque sapien placerat",
    "body": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 58,
    "sender": "Vivi",
    "senderImg": "http://dummyimage.com/183x244.jpg/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-07-09T16:47:48Z",
    "subject": "at nunc commodo placerat praesent blandit nam nulla integer pede",
    "body": "Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 59,
    "sender": "Wilone",
    "senderImg": "http://dummyimage.com/113x100.jpg/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-06-27T03:54:58Z",
    "subject": "maecenas",
    "body": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 60,
    "sender": "Geordie",
    "senderImg": "http://dummyimage.com/184x103.png/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-05-20T13:50:34Z",
    "subject": "turpis",
    "body": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 61,
    "sender": "Justine",
    "senderImg": "http://dummyimage.com/107x177.png/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-12-20T19:28:21Z",
    "subject": "ut mauris eget massa",
    "body": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 62,
    "sender": "Renato",
    "senderImg": "http://dummyimage.com/126x165.bmp/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2020-04-23T07:49:50Z",
    "subject": "ante ipsum primis in faucibus orci luctus et ultrices posuere",
    "body": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 63,
    "sender": "Hunter",
    "senderImg": "http://dummyimage.com/226x201.bmp/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-08-26T03:12:41Z",
    "subject": "velit vivamus vel nulla eget",
    "body": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 64,
    "sender": "Barnett",
    "senderImg": "http://dummyimage.com/109x139.jpg/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-01-24T21:28:14Z",
    "subject": "in blandit",
    "body": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 65,
    "sender": "Norton",
    "senderImg": "http://dummyimage.com/245x181.bmp/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-08-28T14:17:20Z",
    "subject": "aenean lectus pellentesque eget nunc donec quis orci",
    "body": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 66,
    "sender": "Percy",
    "senderImg": "http://dummyimage.com/168x167.png/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-11-11T18:29:32Z",
    "subject": "sem duis aliquam convallis nunc",
    "body": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 67,
    "sender": "Chrystel",
    "senderImg": "http://dummyimage.com/175x237.png/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-05-31T18:26:02Z",
    "subject": "elementum ligula vehicula consequat morbi a ipsum",
    "body": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 68,
    "sender": "Christel",
    "senderImg": "http://dummyimage.com/202x198.jpg/ff4444/ffffff",
    "adjunto": false,
    "sendDate": "2020-07-09T10:14:13Z",
    "subject": "pellentesque ultrices phasellus id sapien in",
    "body": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 69,
    "sender": "Merv",
    "senderImg": "http://dummyimage.com/131x215.bmp/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-02-11T20:30:10Z",
    "subject": "lectus pellentesque at nulla suspendisse potenti cras in",
    "body": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 70,
    "sender": "Rosa",
    "senderImg": "http://dummyimage.com/241x135.bmp/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-06-17T14:28:56Z",
    "subject": "arcu",
    "body": "Fusce consequat. Nulla nisl. Nunc nisl.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 71,
    "sender": "Shea",
    "senderImg": "http://dummyimage.com/129x229.png/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2020-08-12T04:45:48Z",
    "subject": "lorem quisque ut erat curabitur gravida",
    "body": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": false,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 72,
    "sender": "Michelle",
    "senderImg": "http://dummyimage.com/186x163.png/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-08-19T15:49:37Z",
    "subject": "faucibus",
    "body": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": false,
    "category": "promotions",
    "folder": "personal"
  }, {
    "id": 73,
    "sender": "Basil",
    "senderImg": "http://dummyimage.com/145x176.png/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-09-14T09:26:03Z",
    "subject": "sapien",
    "body": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 74,
    "sender": "Melisandra",
    "senderImg": "http://dummyimage.com/234x187.bmp/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-06-20T22:54:54Z",
    "subject": "vestibulum velit id pretium iaculis diam",
    "body": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 75,
    "sender": "Godiva",
    "senderImg": "http://dummyimage.com/140x240.png/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-09-05T18:52:47Z",
    "subject": "ut suscipit a feugiat et eros vestibulum ac est lacinia",
    "body": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 76,
    "sender": "Hollis",
    "senderImg": "http://dummyimage.com/194x187.jpg/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-05-30T23:22:54Z",
    "subject": "turpis elementum ligula vehicula consequat morbi a ipsum integer",
    "body": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 77,
    "sender": "Jaynell",
    "senderImg": "http://dummyimage.com/104x216.png/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-09-01T05:35:48Z",
    "subject": "integer aliquet massa id lobortis convallis tortor risus dapibus augue",
    "body": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 78,
    "sender": "Tiffy",
    "senderImg": "http://dummyimage.com/181x117.bmp/dddddd/000000",
    "adjunto": true,
    "sendDate": "2021-01-05T05:59:58Z",
    "subject": "ullamcorper",
    "body": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 79,
    "sender": "Kalinda",
    "senderImg": "http://dummyimage.com/232x133.jpg/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2021-01-19T15:21:43Z",
    "subject": "turpis adipiscing lorem vitae mattis nibh ligula nec sem duis",
    "body": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 80,
    "sender": "Ram",
    "senderImg": "http://dummyimage.com/242x116.jpg/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-08-10T03:26:41Z",
    "subject": "ut volutpat sapien arcu",
    "body": "Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 81,
    "sender": "Stephan",
    "senderImg": "http://dummyimage.com/116x230.bmp/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-09-01T07:24:23Z",
    "subject": "vivamus in felis eu sapien cursus vestibulum proin eu mi",
    "body": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 82,
    "sender": "Reed",
    "senderImg": "http://dummyimage.com/162x250.jpg/dddddd/000000",
    "adjunto": false,
    "sendDate": "2021-01-14T00:04:07Z",
    "subject": "natoque penatibus et magnis dis",
    "body": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 83,
    "sender": "Marlie",
    "senderImg": "http://dummyimage.com/103x133.bmp/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2021-01-04T01:34:52Z",
    "subject": "nulla suscipit ligula",
    "body": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "social",
    "folder": "discounts"
  }, {
    "id": 84,
    "sender": "Tristan",
    "senderImg": "http://dummyimage.com/122x129.jpg/cc0000/ffffff",
    "adjunto": true,
    "sendDate": "2021-01-15T17:20:53Z",
    "subject": "purus phasellus in felis donec semper sapien a libero nam",
    "body": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 85,
    "sender": "Melosa",
    "senderImg": "http://dummyimage.com/209x187.bmp/5fa2dd/ffffff",
    "adjunto": true,
    "sendDate": "2020-05-07T03:04:53Z",
    "subject": "justo",
    "body": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 86,
    "sender": "Meredith",
    "senderImg": "http://dummyimage.com/192x159.bmp/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-02-10T15:38:55Z",
    "subject": "sed tincidunt eu felis fusce",
    "body": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 87,
    "sender": "Rudolf",
    "senderImg": "http://dummyimage.com/141x105.png/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-07-12T16:16:41Z",
    "subject": "ipsum primis",
    "body": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": false,
    "category": "social",
    "folder": "work"
  }, {
    "id": 88,
    "sender": "Aubrette",
    "senderImg": "http://dummyimage.com/170x237.bmp/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-10-10T13:50:22Z",
    "subject": "vulputate elementum nullam varius nulla",
    "body": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": false,
    "isSent": false,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "promotions",
    "folder": "discounts"
  }, {
    "id": 89,
    "sender": "Brade",
    "senderImg": "http://dummyimage.com/182x138.bmp/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2021-01-19T06:33:28Z",
    "subject": "quisque id justo",
    "body": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 90,
    "sender": "Arel",
    "senderImg": "http://dummyimage.com/233x246.jpg/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-06-30T20:37:33Z",
    "subject": "volutpat eleifend donec ut dolor morbi vel lectus in quam",
    "body": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": true,
    "category": "social",
    "folder": "work"
  }, {
    "id": 91,
    "sender": "Alana",
    "senderImg": "http://dummyimage.com/165x133.jpg/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-08-08T17:11:14Z",
    "subject": "urna pretium nisl ut volutpat",
    "body": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "social",
    "folder": "personal"
  }, {
    "id": 92,
    "sender": "Wiatt",
    "senderImg": "http://dummyimage.com/148x100.jpg/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-07-01T16:39:50Z",
    "subject": "parturient",
    "body": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 93,
    "sender": "Flora",
    "senderImg": "http://dummyimage.com/250x143.bmp/5fa2dd/ffffff",
    "adjunto": false,
    "sendDate": "2020-09-24T16:47:37Z",
    "subject": "nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque",
    "body": "Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": false,
    "isImportant": false,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "work"
  }, {
    "id": 94,
    "sender": "Emilee",
    "senderImg": "http://dummyimage.com/137x203.jpg/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-02-11T12:15:56Z",
    "subject": "turpis a pede posuere nonummy integer non",
    "body": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": false,
    "isImportant": false,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "work"
  }, {
    "id": 95,
    "sender": "Jessie",
    "senderImg": "http://dummyimage.com/192x155.bmp/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-09-24T06:20:54Z",
    "subject": "suscipit a feugiat et",
    "body": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": false,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 96,
    "sender": "Merrill",
    "senderImg": "http://dummyimage.com/240x111.bmp/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-09-19T12:46:22Z",
    "subject": "elit ac nulla",
    "body": "Fusce consequat. Nulla nisl. Nunc nisl.",
    "isFaved": true,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "primary",
    "folder": "discounts"
  }, {
    "id": 97,
    "sender": "Isabelle",
    "senderImg": "http://dummyimage.com/248x145.png/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-08-24T14:12:50Z",
    "subject": "in hac habitasse platea dictumst maecenas ut",
    "body": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": true,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "promotions",
    "folder": "work"
  }, {
    "id": 98,
    "sender": "Audrie",
    "senderImg": "http://dummyimage.com/206x203.bmp/ff4444/ffffff",
    "adjunto": true,
    "sendDate": "2020-02-19T04:52:11Z",
    "subject": "et magnis dis parturient montes nascetur",
    "body": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "isFaved": false,
    "isOpened": true,
    "isSnoozed": false,
    "isDraft": false,
    "isSent": true,
    "isImportant": true,
    "isSelected": false,
    "isDeleted": true,
    "category": "promotions",
    "folder": "personal"
  }, {
    "id": 99,
    "sender": "Tremain",
    "senderImg": "http://dummyimage.com/229x197.png/dddddd/000000",
    "adjunto": false,
    "sendDate": "2020-02-09T06:28:19Z",
    "subject": "est quam pharetra magna ac consequat",
    "body": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    "isFaved": true,
    "isOpened": true,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "primary",
    "folder": "personal"
  }, {
    "id": 100,
    "sender": "Vivian",
    "senderImg": "http://dummyimage.com/132x127.bmp/cc0000/ffffff",
    "adjunto": false,
    "sendDate": "2020-03-28T02:04:45Z",
    "subject": "luctus",
    "body": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    "isFaved": false,
    "isOpened": false,
    "isSnoozed": true,
    "isDraft": true,
    "isSent": false,
    "isImportant": true,
    "isSelected": true,
    "isDeleted": false,
    "category": "social",
    "folder": "discounts"
  }]
`;

// console.log(mails_raw);
const mails = JSON.parse(mails_raw);